### ISSUE TITLE
Long time for spectral cluster

### ISSUE THREAD

**Issue by liudaotan** [pz-white/COM6911-DTI-2021#13]
We tried the spectral clustering which is recommended by haiping. I tried to run it on a small dataset first, there is no errors reported. But when I run it on the full Kd dataset, the clustering process took a whole day with no results, is this acceptable? Would you mind taking a look our code? Thank you. @pz-white 
![spectral](https://user-images.githubusercontent.com/72572210/118019099-8086b700-b350-11eb-8e78-c8c1f2f6552e.png)
?

**Comment by haipinglu** [comment]
You are using all default settings except the number of clusters. You should study the API to understand the various settings and change to a quicker converging setting if you want to reduce the running time (e.g. https://scikit-learn.org/stable/modules/generated/sklearn.cluster.SpectralClustering.html

To be faster
n_init: decrease
n_neighbors: decrease
eigen_tol: increase (to still small values, e.g. 1e-10, 1e-6)
n_jobs: increase
affinity: use precomputed_nearest_neighbors or precomputed, precompute the adjacency matrix and make it sparse and pass the sparse version (inspect the sparsity)

You need to read and understand the API to speed up, rather than just blindly apply.

**Comment by liudaotan** [comment]
Thank you very much. We have found suitable parameters now 👍
